# -*- mode: ruby -*-
# vi: set ft=ruby :

HOST_NAME="oracle"
IP_ADDRESS="192.168.100.12"
SSH_PORT=2212

$script = <<-SCRIPT
set -x
#
if [[ ! "$(rpm -q epel-release)" = "epel-release-"* ]]
then yum install -y epel-release; fi
#
echo HOST_NAME=${HOST_NAME}
echo IP_ADDRESS=${IP_ADDRESS}
#
hostname
hostname -I
SCRIPT
  
Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.4"
  #
  config.vm.network "forwarded_port", guest: 22, host: SSH_PORT, host_ip: "127.0.0.1"
  #
  config.vm.network "forwarded_port", guest: 1521, host: 1521, host_ip: "127.0.0.1" # Listener
  config.vm.network "forwarded_port", guest: 1522, host: 1522, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 5500, host: 5500, host_ip: "127.0.0.1" # Enterprise Manager https://localhost:5500/em
  config.vm.network "forwarded_port", guest: 5501, host: 5501, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 5520, host: 5520, host_ip: "127.0.0.1" # Oracle Enterprise Manager Database Console RMI
  config.vm.network "forwarded_port", guest: 3938, host: 3938, host_ip: "127.0.0.1" # Oracle Management Agent
  #
  config.vm.network "private_network", ip: IP_ADDRESS
  #
  config.vm.hostname = HOST_NAME
  #
  config.vm.synced_folder "../downloads/", "/vagrant/downloads", create: true
  #
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
	vb.cpus = "2"
	vb.name = HOST_NAME
  end
  #
  config.vm.provision "shell", path: "../common/avahi.sh"
  #
  # https://wiki.centos.org/HowTos/Oracle12onCentos7
  #
  config.vm.provision "shell", path: "oracle12c_1_hostname.sh"
  config.vm.provision "shell", path: "oracle12c_2_sestatus.sh"
  config.vm.provision "shell", path: "oracle12c_3_firewall.sh"
  config.vm.provision "shell", path: "oracle12c_4_userdir.sh"
  config.vm.provision "shell", path: "oracle12c_5_config.sh"
  config.vm.provision "shell", path: "oracle12c_6_unzip.sh"
  config.vm.provision "shell", path: "oracle12c_7_yum.sh"
  #config.vm.provision "shell", path: "oracle12c_X_xwindow.sh"
  config.vm.provision "shell", path: "oracle12c_8_install.sh"
  config.vm.provision "shell", path: "oracle12c_8a_postinstall.sh"
  config.vm.provision "shell", path: "oracle12c_8b_profile.sh"
  config.vm.provision "shell", path: "oracle12c_9_createdb.sh"
  config.vm.provision "shell", path: "oracle12c_A_check.sh"
  #
  config.vm.provision "shell",
  env: {
  
	"IP_ADDRESS" => IP_ADDRESS,
	"HOST_NAME" => HOST_NAME
  }, inline: $script
end
