# -*- mode: ruby -*-
# vi: set ft=ruby :
#
HOST_NAME="graphite"
IP_ADDRESS="192.168.100.34"
SSH_PORT=2234
#
$script = <<-SCRIPT
set -x
#
apt-get -q update
#
# https://www.digitalocean.com/community/tutorials/how-to-install-and-use-graphite-on-an-ubuntu-14-04-server
apt-get install -y -q graphite-web graphite-carbon
apt-get install postgresql libpq-dev python-psycopg2
#
sudo -u postgres psql <<SQL
CREATE USER graphite WITH PASSWORD 'passw0rt';
CREATE DATABASE graphite WITH OWNER graphite;
SQL
#
#SECRET_KEY = 'UNSAFE_DEFAULT'
if [ $(grep '^SECRET_KEY' /etc/graphite/local_settings.py | wc -l) -eq 0 ]
then echo "SECRET_KEY = '"$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 64 ; echo '')"'" | sudo tee -a /etc/graphite/local_settings.py; fi
#TIME_ZONE = 'America/Los_Angeles'
if [ $(grep '^TIME_ZONE' /etc/graphite/local_settings.py | wc -l) -eq 0 ]
then echo "TIME_ZONE = 'Europe/Berlin'" | sudo tee -a /etc/graphite/local_settings.py; fi
#USE_REMOTE_USER_AUTHENTICATION = True
sed 's/#USE_REMOTE_USER_AUTHENTICATION = True/USE_REMOTE_USER_AUTHENTICATION = True/' -i /etc/graphite/local_settings.py
#DATABASES ...
sed "s|'NAME': '/var/lib/graphite/graphite.db',|'NAME': 'graphite',|" -i /etc/graphite/local_settings.py
sed "s|'ENGINE': 'django.db.backends.sqlite3',|'ENGINE': 'django.db.backends.postgresql_psycopg2',|" -i /etc/graphite/local_settings.py
sed "s|'USER': '',|'USER': 'graphite',|" -i /etc/graphite/local_settings.py
sed "s|'PASSWORD': '',|'PASSWORD': 'passw0rt',|" -i /etc/graphite/local_settings.py
sed "s|'HOST': '',|'HOST': 'localhost',|" -i /etc/graphite/local_settings.py
sed "s|'PORT': '',|'PORT': '',|" -i /etc/graphite/local_settings.py
#
graphite-manage syncdb ## !!! requires manual input !!! see below
# You just installed Django's auth system, which means you don't have any superusers defined.
# Would you like to create one now? (yes/no): no
#
sed 's/CARBON_CACHE_ENABLED=false/CARBON_CACHE_ENABLED=true/' -i /etc/default/graphite-carbon
sed 's/ENABLE_LOGROTATION = False/ENABLE_LOGROTATION = True/' -i /etc/carbon/carbon.conf
#
echo "[carbon]
pattern = ^carbon\.
retentions = 60:90d

[test]
pattern = ^test\.
retentions = 10s:10m,1m:1h,10m:1d

[default_1min_for_1day]
pattern = .*
retentions = 60s:1d
" |
  sudo tee /etc/carbon/storage-schemas.conf
#
cp -v /usr/share/doc/graphite-carbon/examples/storage-aggregation.conf.example /etc/carbon/storage-aggregation.conf
#
#  UsageError("Unknown command: %s" % sub)
mv -v /usr/local/lib/python2.7/dist-packages/twisted /usr/local/lib/python2.7/dist-packages/twisted2
#
service carbon-cache start
#
apt-get install -y -q apache2 libapache2-mod-wsgi
#
a2dissite 000-default
cp -v /usr/share/graphite-web/apache2-graphite.conf /etc/apache2/sites-available
a2ensite apache2-graphite
service apache2 reload
#
echo "test.count 42 `date +%s`" | nc -q0 127.0.0.1 2003
#
# http://localhost:8088
#
SCRIPT
# 
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  #
  config.vm.network "forwarded_port", guest: 22, host: SSH_PORT, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 80, host: 8088, host_ip: "127.0.0.1"
  #
  config.vm.network "private_network", ip: IP_ADDRESS
  #
  config.vm.hostname = HOST_NAME
  #
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
	vb.cpus = "2"
	vb.name = HOST_NAME
  end
  #
  config.vm.provision "shell",
  env: {
	"IP_ADDRESS" => IP_ADDRESS,
	"HOST_NAME" => HOST_NAME
  }, inline: $script
  #
end
