# -*- mode: ruby -*-
# vi: set ft=ruby :
#
HOST_NAME="consul"
IP_ADDRESS="192.168.100.31"
SSH_PORT=2231
#
$script = <<-SCRIPT
set -x
#
if [[ ! "$(rpm -q epel-release)" = "epel-release-"* ]]
then yum install -y epel-release; fi
#
echo HOST_NAME=${HOST_NAME}
echo IP_ADDRESS=${IP_ADDRESS}
#
hostname
hostname -I
#
ZIP="consul_1.0.7_linux_amd64.zip"
if [ ! -f consul_1.0.7_linux_amd64.zip ]
then
  URL="https://releases.hashicorp.com/consul/1.0.7"
  wget -q $URL/$ZIP -O $ZIP
fi
ls -l $ZIP
#
if [[ ! "$(rpm -q unzip)" = "unzip-"* ]]
then yum install -y unzip; fi
mkdir -p /opt/consul
unzip $ZIP -d /opt/consul/
#
if [ "$(grep 'PATH=$PATH:/opt/consul' /etc/profile | wc -l)" -eq 0 ]
then echo -e "\n"'export PATH=$PATH:/opt/consul' | tee -a /etc/profile; fi
source /etc/profile
#
consul --version
#
consul agent -dev -ui -client 0.0.0.0 >> consul.agent.stdout 2>> consul.agent.stderr &
#
sleep 5
#
consul members
#
curl localhost:8500/v1/catalog/nodes
#
if [[ ! "$(rpm -q bind-utils)" = "bind-utils-"* ]]
then yum install -y -q bind-utils; fi
#
dig @127.0.0.1 -p 8600 $(hostname).node.consul
#
# http://localhost:8500/ui
#
SCRIPT
# 
Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.4"
  #
  config.vm.network "forwarded_port", guest: 22, host: SSH_PORT, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 8500, host: 8500, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 8600, host: 8600, host_ip: "127.0.0.1"
  #
  config.vm.network "private_network", ip: IP_ADDRESS
  #
  config.vm.hostname = HOST_NAME
  #
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
	vb.cpus = "2"
	vb.name = HOST_NAME
  end
  #
  config.vm.provision "shell", path: "../common/avahi.sh"
  #
  config.vm.provision "shell",
  env: {
	"IP_ADDRESS" => IP_ADDRESS,
	"HOST_NAME" => HOST_NAME
  }, inline: $script
  #
end
